import datetime
from .client import *

origin = """
We define "narrowed subject" as the following situations: 
1. singular specific nouns. e.g. "sun", "Mike", "HIV virus", "this football".
2. variables. e.g. "x", "y".
3. plural nouns that are not composed of a single individual. e.g. "pants", which is not composed of any individual, but it is plural.
4. Other plural nouns that meet the following conditions:  The object of the sentence in which this plural noun is placed is a singular noun. For example, "Birds are a type of animal.", of which the object "a type of animal" is a singular noun, so the subject "birds" of this sentence is a narrowed subject. However, in "Birds can fly.", there is no object, so this "bird" is not a narrowed subject; for another example, in "Birds are cute.", there is no object of a singular noun, so this "birds" is not a narrowed subject. Therefore, whether a plural noun expressing a plurality of individuals is a narrowed subject requires considering the object of the sentence.
In the future, you will modify the sentence according to certain rules. The subject of the modified sentence must be a narrowed subject.

Let's define the "generalized verb" in the sentence: 
we call the entire structure of a verb after it has been transformed into voice, tense, adverb, and modal, and take into account the preposition that follows the verb, and the collocation of verbs and prepositions. For example, "moved to" in "I moved to Beijing"; "was created by" in "This game was created by me"; "am eating" in "I am eating."; "can fly" in "I can fly"; "share … with …" in "Mike shares his ball with John."; "assign … to …" in "Prof. Li assigned task A to Mike.".
Note:
1. The generalized verb cannot contain adjectives.
2. Generalized verbs can be phrases such as "is a type of" and "are a product of", but cannot be phrases such as "are two types of" and "is two products of".
3. The generalized verb should consider all consecutive prepositions as much as possible. For example, "move away" in "He moved away in 1911." is followed by an "in", so it is also included in the generalized verb, that is, the generalized verb is "move away in". 
4. Now you know about narrowed subjects and generalized verbs. In the future, I will teach you to modify sentences according to certain rules. The modified sentences must have narrowed subjects and generalized verbs. And in a sentence, the generalized verb must come after the narrowed subject.

Let's define "narrowed object": 
1. an adjective word. e.g. "cute" in "dogs are cute.", it is an adjective word, so it is a narrowed object. Other examples: "handsome", "still", "scary", etc.
2. a singular noun (it doesn't have to be a specific noun, for example, "a cow" in "I have a cow" is a narrowed object.). For example, "2001", "Mike", "food".
4. variables, like "x", "y".
5. plural nouns that are not composed of a single individual. e.g. "pants", which is not composed of any individual, but it is plural. 
Notes: 
1. Not every sentence has a narrowed object, but if there is a narrowed object, it must immediately follow the generalized verb.  Therefore, when you want to identify the narrowed object in a sentence, you should first look for the generalized verb in the sentence, and then see if the component immediately after it is one of the several situations in the above definition. 
2. We have mentioned generalized verbs that consider verb-preposition collocations. Generally speaking, a sentence containing such a generalized verb needs to have two narrowed objects. For example, "Prof. Li assigned task A to someone.", the generalized verb is "assigned... to...", then, consider the words "task A" and "someone" in the middle and behind it, they all conform to the definition of narrowed object, so they are the narrowed object of this sentence.
3. The narrowed object is not necessarily the same as the object in linguistics. You don't need to think according to the object in linguistics. It doesn't have to be a noun. You only need to follow the method I mentioned above to determine the narrowed object of the sentence.
4. Please consider some lengthy yet legitimate narrowed objects, without breaking them apart, such as "a private Ivy League research university.", clearly, this is a singular noun phrase and can serve as a narrowed object.

Examples (Here you learn to find whether a sentence has a narrowed object or which one is.):
1. "This cup was broken by Mike.", the generalized verb is "was broken by", and the following word is "Mike", which conforms to one of the narrowed objects, so the narrowed object of this sentence is "Mike";
2. "I left in 1911.", the generalized verb is "left in", followed by "1911", which conforms to one of the above situations, so the narrowed object is "1911";
3. "iPhone 13 is a product of Apple.", the generalized verb is "is a product of", followed by "Apple", which is a singular noun, consistent with the above situation, so the narrowed object of this sentence It's "Apple".
4. "Mike is handsome.", the generalized verb is "is", followed by "handsome", which is an adjective, so the narrowed object is "handsome". 
5. "Mike has cake A and cake B.", the generalized verb is "has", followed by "cake A and cake B", which is not a singular noun, so there is no narrowed object in this sentence.
6. "Mike shares his ball with John.", the generalized verb is "shares … with …", then, consider the words "his ball" and "John" in the middle and behind it, they all conform to the definition of narrowed object, so the narrowed objects of this sentence are "his ball" and "John".

Let's analyze some sentences:
1. "y is still.", "y" is a variable, a narrowed subject, the generalized verb is "is", followed by "still", which is an adjective, so the narrowed object is "still".
2. "Some dogs like ball.", "some dogs" is plural, but it is composed of individuals, so it is not a narrowed subject. The generalized verb is "like", followed by "ball", which is a singular is a noun, so the narrowed object is "ball".
3. "Animals are scary.", "animals" is a plural noun, and the object is not singular, so it is not a narrowed subject; the generalized verb is "are", followed by "scary", which is an adjective, so it is narrowed the object is "scary".
4. "I have certain pets.", the narrowed subject is "I", the generalized verb is "have", followed by "certain pets", which means part or some, so it is not a narrowed object.
5. "iPhone 13 is a product of Apple.", the narrowed subject is "iPhone 13" (a singular specific noun), the generalized verb is "is a product of", followed by "Apple", which is a singular noun, consistent with the above situation, so the narrowed object of this sentence is "Apple".

Then, we can start to build a natural language logic system (NLL System).
First, define atomic sentences. 
The following three forms of sentences are called atomic sentences:
1. A sentence with and only with three components: a narrowed subject, a generalized verb, and a narrowed object (we call it the "SVO" structure.). For example, "I am cute.". But "dogs are cute." is not the case because the subject "dogs" is not a narrowed subject.
2. A sentence with and only with four components: a narrowed subject, a generalized verb, and two narrowed objects (we call it the "SVOO" structure.), of which the generalized verb can contain two narrowed objects. For example, "Mike shares his ball with John.", "Mike" is a narrowed subject, the generalized verb is "shares … with …" which can contain two narrowed objects, and the narrowed objects are "his ball" and "John".
3. A sentence with and only with two components: a narrowed subject and a generalized verb (we call it the "SV" structure). For example, "Mike can fly." But "Birds can fly." is not such a structure because its subject "birds" is not a narrowed subject.
Please note that when you want to determine whether a sentence is an atomic sentence, please first analyze the components of the sentence. Please check whether it is an SVO structure or an SVOO structure first, and then check whether it is an SV structure. Not all sentences are atomic sentences, and some sentences are not atomic sentences.
Example:
1. "I moved to Beijing in 1911.", the narrowed subject is "I", the generalized verb is "moved to … in …", followed by "Beijing" and "1911" in the middle and behind it, they all conform to the definition of narrowed object, so the narrowed objects of this sentences are "Beijing" and "1911". This sentence is with and only with a narrowed subject, a generalized verb and two narrowed objects, so it is a SVOO structure atomic sentence.
2. "Amy is pretty.", the narrowed subject is "Amy", the generalized verb is "is", followed by "pretty"(an adjective), so it's a narrowed object. This sentence has these three components and no additional components, so it is an SVO structure.
3. "New York Zoo has certain animals", the narrowed subject is "New York Zoo", the generalized verb is "has", followed by "certain animals", which means part or some of animals, not any case of narrowed object, so this sentence is not a SVO structure. But in addition to narrowed subject and generalized verb, it has other redundant components, and it is not an SV structure.
4. "Animals are terrible.", "animals" is a plural noun, and the object of this sentence is not a singular, so "animals" is not a narrowed subject, then this sentence can't be SVO or SV structure, then it is not an atomic sentence.
5. "Amy is a singer or a player.", the narrowed subject is "Amy", the generalized verb is "is", followed by "a singer or a player", which dose not conform the definition of the narrowed subject, so this sentence does not have narrowed object, so this sentence can't be any atomic sentence.
6. "Mike is the students who likes books.", in this sentence, the subject in the narrow sense is "Mike", the verb in the broad sense is "is", followed by "the student who likes books." which is a singular noun containing an attributive clause, also not in our narrow definition of object. Therefore, this sentence does not have a narrowed object and has other components besides the narrowed subject and the generalized verb, so this is not an atomic sentence.

The next step is to define standard sentences. The following situations are called standard sentences:
1. Assume that NL1 is a SVO structure atomic sentence, then "(NL1)" is a standard sentence.
2. Assume that NL1 is a SVOO structure atomic sentence, then "(NL1)" is a standard sentence.
3. Assume that NL1 is a SV structure atomic sentence, then "(NL1)" is a standard sentence.
4. Assume that NL1 and NL2 are standard sentences, then "(NL1 and NL2)" is a standard sentence. For example, consider NL1 = "(Mike is rich.)", NL2 = "(I can fly.)", NL1 is an atomic sentence with SVO structure, NL2 is an atomic sentence with SV structure, then "((Mike is rich.) and (I can fly.))" is a standard sentence.
5. Assume that NL1 and NL2 are standard sentences, then "(NL1 or NL2)" is a standard sentence. For example, consider NL1 = "(Mike is rich.)", NL2 = "(I can fly.)", NL1 is an atomic sentence with SVO structure, NL2 is an atomic sentence with SV structure, then "((Mike is rich) or (I can fly.))" is a standard sentence.
6. Assume that NL1 and NL2 are standard sentences, then "(If NL1, then NL2)" is a standard sentence. For example, consider NL1 = "((Mike has money) and (I can fly.))", NL2 = "(I have money.)", NL1 is the third standard sentence, NL2 is an SVO structure atomic sentence, then "(If ((Mike has money) and (I can fly.)), then (I have money.))" It's a standard sentence.
7. Assume that NL1 is a standard sentence, then "(for all x, NL1)" is a standard sentence. For example, consider NL1 = "(If (x is an animal), then (x is cute.))", NL1 is the fifth type of standard sentence, then "(for all x, (if (x is an animal), then (x is cute.)))" is the standard sentence.
Note:
1. The above definition is obviously a recursive definition, so please strictly note that atomic sentences conform to the definition of atomic sentence. Please think carefully about the narrowed subject, generalized verb and narrowed object in the sentence. 
2. Please pay attention to the sentences on both sides of "or" and "and", the two sentences sandwiched by "if-then", and the sentences after "for all x," should be standard sentences.
3. Note that the sentence inside each bracket is a standard sentence.

This system has the "uniqueness of standard sentence readability" theorem, which stipulates that any sentence must be in one of the above six forms, or can be rewritten into one of the above six forms.
Example:
1. "Mike is fat." is a sentence with SVO structure. We rewrite it as "(Mike is fat.)" and it becomes a standard sentence.
2. "She is a singer or a player.", "She" is a narrowed subject, and the generalized verb is "is", but the following "singer or player" is not a singular number, that is, it is not a narrowed object; in the sentence, there are other components, so it is not an atomic sentence of SVO or SV structure. And the two sides of his "or" are not standard sentences. Therefore, this sentence is not a standard sentence. However, we could rewrite it as "((She is a singer) or (she is a player.))" which would make it the third of the six forms.
3. "Amy Bing is the student who dislikes mathematics." The narrowed subject is "Amy Bing" and the generalized verb is "is". However, "the student who dislikes the student" is not a narrowed object; it contains an attributive clause. It's easy to see that it doesn't fit into one of the six forms. In natural language, this already implies that Amy is a student. What really matters is whether Amy Bing likes reading, so we can change it to "(Amy Bing dislikes reading books.)"
4. "Birds can fly." The subject of this sentence is not a narrowed subject, but its subject refers to all the birds in the entire flock. This situation is called the "for-all pattern" and needs to be reiterated by introducing a universal quantifier. It can be rewritten as "(for all x, (if (x is a bird), then (x can fly.)))", thus becoming the sixth form. This situation must be translated into "if-then" format (for example, "all birds are cute" is translated into "(for all x, (x is a bird and x is cute))" which is wrong, and the correct one is "(for all x, (if (x is a bird), then (x is cute)))". **Note**: In the future, when I give you a list to deal with, considering the discourse domain of the list content, this sentence can also be modified to "(for all x, (x can fly.))". As for whether to modify it to the above method or here, please refer to the Rule5 carefully.
5. "Some teachers like books.", "Some teachers" is not specifically singular, but it does not mean "all." This situation is called "existential mode" and requires the introduction of an existential quantifier to assist rewriting, then it can be rewritten as "(((There is an x) and (x is a teacher)) and (x likes books.))", in which case the sentence is of the third type.
6. "Mike moved to Beijing in 1715.", the narrowed subject of this sentence is "Mike", and the generalized verb is "moved to ... in ...", which is a generalization that can include two narrowed objects. verb. Consider "Beijing" and "1715" in the sentence, they both meet the definition of narrowed objects, so the narrowed objects of this sentence are them. This sentence has a narrowed subject, a generalized verb, two narrowed objects, and no other components, so it is an SVOO structure atomic sentence, and the standard sentence form is "(Mike moved to Beijing in 1715.)"
7. "Some people are not shooters.", "some people" means part of people, so this is a "existential mode". So, it is modified as "(((there exists x) and (x is a people)) and (x is not a shooter.))".
8. "If an employee has money, he will go shopping.", such a sentence already has an "if-then" structure, and we can first process it as "(If (an employee has money), then (he will go shopping.))". Let's say NL1 = "(an employee has money)" and NL2 = "(he will go shopping.)". NL1 is not a standard sentence because "an employee" does not meet the definition of a narrowed subject, but we can modify it to "((x is an employee) and (x has money.))", and NL2 can also be modified to "(x will go shopping.)", the sentence becomes "(if ((x is an employee) and (x has money.)), then (x will go shopping.))". But we want to emphasize that this is for all employees, so we can finally change it to "(for all x, (if ((x is an employee) and (x has money.)), then (x will go shopping.)))", this is a standard sentence.
9. "When a person reads a book, the person gains knowledge.", consider a x, in this sentence, we don't care whether x is a person, so we can modify it to "(for all x, (if (x read a book), then (x gains knowledge.)))".
10. "Some birds exist.", it's easy to modify to "((there exists x) and (x is a bird.))". It's wrong to say "x exists".
11. "Mike is not a bird.", the generalized verb is "is not". It's easy to modify to "(Mike is not a bird.)".
The above modifications are not final, because you will be dealing with a paragraph containing multiple sentences that share the same topic, so further modifications may be needed, such as domain processing and contextual wording unification.

Your job is to modify the sentences to be a standard format. There are some rules for you when you modify sentences: (There are 10 rules marked as Rule1 – Rule10):
Rule1. Please don't ignore the parentheses in the definition of a standard sentence, they are all a standard sentence inside. And if you are going to use variables, please only use x, y, z.
Rule2. Generally, a singular noun not specifying a specific object or a plural noun not modified by any word refer to the whole of what they represent. For example, "a man" in "if a man is hairy, he is ugly" refers to "all men"; therefore, in this case, this sentence needs to be modified to "(for all x, (if ((x is a man) and (x is hairy)), then (x is ugly.)))". Another example "If an employee has money, then he will go shopping." should be modified as "(for all x, (if ((x is an employee) and (x has money.)), then (x will go shopping.)))". Including, words like "everyone" should be understood to mean everyone. Another example, in the phrase "people eat food.", it does not mean "people" as a group "eat food", but each person "eats food". However, never modify proper nouns, even if they are in the singular, such as "Mike", "sun", some names of people, countries, institutions, diseases, etc.
Rule3. Please do not dismantle the narrowed subject and narrowed object. Don't revise specific nouns, name of person, name of organization, such as "sun", "Mike", etc. For example, "sun is pretty.", you cannot say "there is x and x is a sun.". Please double-check proper nouns, such as "Mike de Duke," "private Ivy school.", "the winner of the 1992 du Maurier Classic" (in a given game, the winner is only one), "The Olympic games", "The number 35", "Symphony No. 9", "professional wrestling stable", do not dismantle them. For example, we said "Dried Thai chilies are a product of Baked by Melissa.", in this sentence, "dried Thai chilies" is a narrowed subject (because the object of this sentence is a singular), you cannot disassemble it into "(for all x, (x is a dried Thai chili))". Please use your common sense to identify all possible proper nouns. 
Rule4. Pay attention to sentences that imply "part". For example, in the phrase "I went to some places.", the object "some places" is not specific, so this sentence is "existential mode". So, it should be modified to "(((there exists x) and (x is a place)) and (I went to x.))".
Rule5. You should consider the domain of discourse problem. If the entire list discusses a specific domain, you don't need to explicitly mention that term. For example: ["Birds can fly", "Dogs like meat", "Animals are either birds or dogs."], since the domain being discussed is about animals, you don't need to explicitly state that x is an animal when modifying the third sentence; 
However, if a list discusses multiple domains, it's necessary to explicitly mention each term. For example, in ["Some trees are green.", "Birds can fly", "Dogs like meat", "Animals are either birds or dogs."], the domains of this list are animals and plants, so you must explicitly state that x is an animal when modifying the third sentence, because if you don't use this term, we won't know whether x is an animal or a plant. 
   - To accomplish this step, we first define three scenarios for the domain: i. The domain consists of only one entity; ii. The domain consists of multiple entities, but one of them includes all others, such as ["animals," "cats," "dogs,"] where "animals" includes the other two; iii. Other scenarios not covered by the first two. 
   - Next, you should follow several steps: 
i. Consider the domains in this list, noting that domains refer to abstract or specific entities, what we consider is the domains of all sentences of a list and there can be more than 1 domain in a single sentence; 
ii. Check if there is only one domain. If yes, refrain from explicitly using the term representing that domain (or its synonyms). 
iii. If the condition in ii is not met, consider if it falls under the second scenario for domains. If it does, refrain from using the term that encompasses others (or its synonyms). Take care of the containment relationship between the domains.
- There are some examples for you:
i. ["Chinese can fly.", "Some Japanese eat meat.", "a person is either a Chinese or a Japanese."], the domain of the first sentence is "Chinese", the second sentence is "Japanese", and the third sentence is "people/persons/individuals/humans, Chinese, Japanese"; in general, the domains of this list is "Chinese, Japanese, people", where "people" includes "Chinese" and "Japanese", so the variable x here is a person, we don't have to say "x is a person."(or 'human'/'person'/'individual', which are "person"'s synonyms), so you just need return ["(for all x, (if (x is a Chinese), then (x can fly.)))", "(((there exists x) and (x is a Japanese)) and (x likes meat))", "(for all x, ((x is a Chinese) or (x is a Japanese.)))"]; in the third sentence, I don't say 'if x is a person', which is not necessary here.
ii. ["If people purchase tickets for the annual concert, then they either enjoy classical music or are students at the music academy.", "All students studying classical music at the music academy are purchasers of tickets for the annual concert.", "If someone plays an active role in community service and frequently participates in volunteer activities, then they are either students at the school or prominent leaders in their community."], the domain of the first sentence includes "people," "tickets," "classical music," and so on. However, we can see that this list mainly discusses kinds of people, so the domain of the first sentence is "people, students.", the domain of the second sentence is "students, purchasers." The domain of the third sentence includes "people, students, leaders"; overall, the domain includes "people, students, purchasers, leaders," where "people" encompasses the other domains. Therefore, do not use phrases like "x is a person."
- Please strictly check the domain of discourse and delete unnecessary judgments about variables. This is important for subsequent reasoning.
Rule6. There are several types of sentences, please modify them according to the following pattern: 
i. sentences like "Mike's favorite animals are different from Amy's." means "There is an animal that Mike likes, but Amy does not like this animal."
ii. sentences like "I have a game the Mario Adventure.", means "((the Mario Adventure is a game) and (I have the Introduction.))". Please take care of this kind of sentences.
iii. Sentences like "I went to certain places, including Beijing.", it must be modified to "((((there exists x) and (x is a place)) and (I went to x)) and ((Beijing is a place) and (I went to Beijing)))"; another example, "I chose certain animals, including humans.", it should be modified as "((((there exists x) and (x is an animal)) and (I chose x)) and ((for all y, (if (y is human), then (y is an animal))) and (I chose y))))". Please note that the subject of our sentence must be a narrowed subject, and the object must be narrowed object. Pay attention to words that indicate "part", like "some", "certain", etc.
iv. Suppose there is something called A, and its plural form is 'As'. When we say "There are n As: T1, T2, ..., Tn" it means "T1 is a A, T2 is a A, ..., Tn is a A." (A is fully instantiated). For example, "There are five countries: China, North Korea, Japan, South Korea, and Mongolia." should be modified as "(((((China is a country) and (North Korea is a country)) and (Japan is a country)) and (South Korea is a country)) and (Mongolia is a country.))". Another example, "There are three animals: birds, dogs, and cats.", you first understand that "birds are animals, dogs are animals, and cats are Animals." Then there are further modifications, because their subjects are not a narrowed subject.
Rule7. Please note the deletion of the attributive clause. We modify the attributive clause by retaining key information. For example, "all people who are inactive are still.", in natural language, the key meaning of "all people who are inactive" is "somebody is inactive". If we consider a variable x, we do not need to emphasize that it is "person", because natural language implies such information; so "all people who are inactive" can be decomposed into "for all x, x is inactive." In this way, the entire sentence becomes "(for all x, (if (x is inactive), then (x is still.)))"; Another example, "Amy is not a student who likes to read", in natural language, this already implies "Amy is a student", we do not need to emphasize it anymore, so this sentence was changed to "Amy doesn't like to read.". "Mike is not a student who likes books.", in natural language, this sentence implies "Mike is a student", so we don't care about this, so we modify this sentence to "Mike doesn't like books.". Get rid of all attributive clauses; otherwise, your translation maybe wrong!
Rule8. My input will be a list. You read and modify it sentence by sentence. Each modification should refer to the modification of the previous sentence to maintain the unity of modifications in the entire list. For example ["Someone made cake A.", "Cake B was made by John.", "Amy created cake C."], the first sentence is modified to "((there exists x) and (x made cake A.))", then you need to modify the second sentence. Theoretically, it is "(Cake B was made by John.)", but for the same word, the first sentence is active and the second sentence is passive, so change the personality here as active, it becomes "(John made cake B)"; then modify the third sentence. There is a generalized verb "created", but we know that the effect of 'make' and 'create' here is the same, so the third sentence is translated as "Amy made cake C.", thus, you return ["((there exists x) and (x made cake A.))", "(John made cake B)", "(Amy made Cake C.)"].
Rule9. Please ensure that the revised sentence is equivalent to the original sentence as much as possible. Of course, it is permissible that we lose a bit of information when it comes to dealing with domain of discourse situations, attributive clause situations, and contextual agreement issues.
Rule10. You're dealing with natural language, so put it into context. 
i. For example ["Mike's favorite animal is a dog.", "Mike and Amy like different things."], the first sentence is already in the standard form, but for the second sentence, combined with the above, the word "like" is discussed should be the favorite animal, so you need to change the second sentence to "(for all x, ((Mike's favorite animal is x) and (Amy's favorite animal is not x.)))". This requires you to think about some common-sense knowledge. For example ["Mike's departure place and destination are different.", "Mike is going to Beijing.", "Mike left from New York."], combined with the context, the "departure place" here should be understood as "the place where Mike left", "Destination" should be understood as "where Mike is going", so the first sentence is modified to "(for all x, (if Mike is going to x, then Mike does not leave from x) and (if Mike leaves from x, Then Mike doesn't go x))". Another example is ["Mike is on the list.", "Amy is selected to the list."], the first sentence is modified to "(Mike is on the list.)", and the second sentence implies "Amy is on the list." , so imitate the first sentence and change the second sentence to "(Amy is on the list.)".
ii. Again, there are a few things to put into context. Some "adjective + noun" structures need to be split and combined into the entire sentence list. For example, for ["Mike is a popular bird.", "There are popular birds."], at this time, "popular bird" is the topic of discussion, and there is no need to separate it; but ["Mike is a popular bird.", "Birds exist."], what is being discussed at this time is "birds", and "popular birds" should be separated into two things: "popular" and "birds", so the first sentence change to "((Mike is popular) and (Mike is a bird.))".

I provide you with a list of natural language non-standard form sentences to be modified. Please only return a modified python-format list without any other explanation. That is, your answer must start with a left square bracket '[' and end with a right square bracket ']'. Please check carefully whether your modified sentences fully comply with the NLL System. Convert the following sentence list:

"""


def process(
    id: int, full_premises: str, list_premises: list, k_list: list, k_dict: dict
):
    global origin
    # 遍历每一个list在k_dict构建提示
    knowledge = "\n".join(k_dict[full_premises])
    prompt = origin.format(
        knowledge=knowledge, length=len(list_premises), full_premises=full_premises
    )
    print(f"ID{id}转化中间语言 {datetime.datetime.now()}: \n{prompt}")
    raw_response = llm_send(prompt, "")
    print(raw_response)
    if raw_response == "":
        return f"ID{id}回复为空", []
    str_res, list_res = process_response(raw_response)
    return str_res, list_res
